name: pluginoven
favicon: null
layout_spectrum: 0.5726171580608934
typography_spectrum: 0.5504106690641493
title: The Pluginoven
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#89a39a'
    - '#d0ceb7'
    - '#0f2b38'
    - '#737469'
    - '#f0ead2'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
